### ISSUE TITLE
Fetchcord doens't open

### ISSUE THREAD

**Issue by Matheus1300** [MrPotatoBobx/FetchCord#90] opened 2020-08-31 15:30 UTC
When i try to run fetchcord appear this:

'neofetch' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
Traceback (most recent call last):
  File "c:\users\matheus lima\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\matheus lima\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\matheus lima\AppData\Local\Programs\Python\Python38-32\Scripts\fetchcord.exe\__main__.py", line 4, in <module>
  File "c:\users\matheus lima\appdata\local\programs\python\python38-32\lib\site-packages\fetch_cord\run_rpc.py", line 10, in <module>
    from fetch_cord.testing import gpuid, cpuappid, appid
  File "c:\users\matheus lima\appdata\local\programs\python\python38-32\lib\site-packages\fetch_cord\testing.py", line 5, in <module>
    from fetch_cord.out import cpumodel, cpuvendor, gpuvendor, sysosid, neofetchwin, baseinfo
  File "c:\users\matheus lima\appdata\local\programs\python\python38-32\lib\site-packages\fetch_cord\out.py", line 242, in <module>
    sysosid = sysosline[0].split()[1]
IndexError: list index out of range

**Comment by byReqz** [comment] 2020-09-06 15:00
same here, running on Windows 10 1909. Works fine on my Arch machine

**Comment by MrPotatoBobx** [comment] 2020-09-13 05:46
ill try to fix window ssoon please use issue templates

**Comment by BlivionIaG** [comment] 2020-11-23 10:42
Hi, does it work now ? It should have been fixed a while ago by now, i'm closing this in a week or two if I don't get a response.

**Comment by byReqz** [comment] 2020-12-25 22:43
runs but doesnt recognize properly
![image](https://user-images.githubusercontent.com/32552517/103142828-8a41b200-4702-11eb-914f-854d4fc8b2ac.png)

**Comment by MrPotatoBobx** [comment] 2020-12-27 07:53
ill see what the issue is, can you send the output of winfetch?

**Comment by MrPotatoBobx** [comment] 2021-01-09 09:11
I'm still waiting

**Comment by byReqz** [comment] 2021-01-15 21:15
sorry for the late reply, this is neofetch from choco
![image](https://user-images.githubusercontent.com/32552517/104779259-b0dd9080-5776-11eb-9ac5-cf593efd2485.png)

**Comment by BlivionIaG** [comment] 2021-03-14 22:39
Hello, did you tried the latest release ? I'll close this in one month if there are no reply by then.

**Comment by byReqz** [comment] 2021-03-17 21:48
![image](https://user-images.githubusercontent.com/32552517/111543059-6f636480-876a-11eb-93a0-30e7b49f4b3e.png)
still the same as before

**Comment by BlivionIaG** [comment] 2021-06-10 18:21
It's probably resolved as it is now.

**Closed by BlivionIaG** 2021-06-10 18:21 UTC
Labels: bug
